"use client"

import { useState, useEffect, useMemo } from "react"
import {
  Copy,
  Check,
  ArrowRight,
  ArrowLeft,
  Download,
  Loader2,
  Zap,
  Eye,
  Sparkles,
  Target,
  AlertTriangle,
  Lightbulb,
  Filter,
} from "lucide-react"
import type { FeedbackItem } from "@/lib/deepseek"
import FeedbackModal from "@/components/feedback-modal"
import { createPdfBlob, downloadPdf, createFeedbackSections } from "@/lib/pdf-utils"

interface FeedbackPageProps {
  resumeData: {
    skills: string[]
    experience: Array<{ company: string; role: string; duration?: string; description?: string }>
    education: Array<{ school: string; degree: string; year?: string }>
    summary?: string
    analysis?: any
  }
  onNext: (data: any) => void
  onPrevious: () => void
}

// PDF generation now handled by shared utility in lib/pdf-utils.ts

export default function FeedbackPage({ resumeData, onNext, onPrevious }: FeedbackPageProps) {
  const [feedbackItems, setFeedbackItems] = useState<FeedbackItem[]>([])
  const [isLoading, setIsLoading] = useState<boolean>(true)
  const [error, setError] = useState<string | null>(null)
  const [fetchVersion, setFetchVersion] = useState(0)
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [activeFilter, setActiveFilter] = useState("all")
  const [isModalOpen, setIsModalOpen] = useState(false)

  const payload = useMemo(
    () => ({
      resume: {
        skills: resumeData.skills,
        experience: resumeData.experience,
        education: resumeData.education,
        summary: resumeData.summary,
      },
      analysis: resumeData.analysis,
    }),
    [resumeData.skills, resumeData.experience, resumeData.education, resumeData.summary, resumeData.analysis],
  )

  const payloadKey = useMemo(() => JSON.stringify(payload), [payload])

  useEffect(() => {
    let isActive = true
    const controller = new AbortController()

    async function fetchFeedback() {
      setIsLoading(true)
      setError(null)

      try {
        const response = await fetch("/api/feedback", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
          signal: controller.signal,
        })

        if (!response.ok) {
          const message = await response.json().catch(() => ({ error: "Feedback request failed" }))
          throw new Error(message?.error || "Feedback request failed")
        }

        const { feedback } = await response.json()
        if (isActive) {
          setFeedbackItems(feedback || [])
          setFetchVersion((value) => (value === 0 ? value : 0))
        }
      } catch (err: any) {
        if (err?.name === "AbortError") return
        if (isActive) {
          setError(err?.message || "Unable to generate feedback right now.")
          setFeedbackItems([])
        }
      } finally {
        if (isActive) {
          setIsLoading(false)
        }
      }
    }

    fetchFeedback()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [payloadKey, fetchVersion])

  const categories = useMemo(() => {
    const cats = new Set<string>()
    feedbackItems.forEach((item) => cats.add(item.category))
    return ["all", ...Array.from(cats).sort()]
  }, [feedbackItems])

  const filtered = useMemo(() => {
    if (activeFilter === "all") return feedbackItems
    return feedbackItems.filter((f) => f.category === activeFilter)
  }, [feedbackItems, activeFilter])

  const handleRetry = () => {
    setFetchVersion((version) => version + 1)
  }

  const handleCopy = (id: string) => {
    const item = feedbackItems.find((f) => f.id === id)
    if (item) {
      navigator.clipboard.writeText(`${item.title}\n\n${item.description}`)
      setCopiedId(id)
      setTimeout(() => setCopiedId(null), 2000)
    }
  }

  const handleDownloadFeedback = () => {
    if (feedbackItems.length === 0) return

    // Use shared PDF utility with proper styling
    const sections = createFeedbackSections(feedbackItems)

    const metadata = {
      title: "CVisionAI Feedback Summary",
      subtitle: "Actionable Resume Feedback & Suggestions",
      generatedAt: new Date(),
      footer: "Generated by CVisionAI - AI-Powered Resume Analysis Tool | Confidential Report - For personal use only",
    }

    const pdfBlob = createPdfBlob(sections, metadata)
    const filename = `cv-feedback-${new Date().toISOString().split("T")[0]}.pdf`
    downloadPdf(pdfBlob, filename)
  }

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "high":
        return "bg-error/10 dark:bg-error/20 text-error dark:text-white border-error/20 dark:border-error/30"
      case "medium":
        return "bg-secondary/10 dark:bg-secondary/20 text-secondary dark:text-white border-secondary/20 dark:border-secondary/30"
      case "low":
        return "bg-primary/10 dark:bg-primary/20 text-primary dark:text-white border-primary/20 dark:border-primary/30"
      default:
        return "bg-muted dark:bg-muted text-muted-foreground dark:text-muted-foreground border-border dark:border-border"
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <div className="flex-1 py-4 sm:py-6">
        <div className="max-w-6xl mx-auto px-3 sm:px-4 md:px-6 w-full space-y-4 sm:space-y-6 overflow-hidden">
          {/* Enhanced Header */}
          <div className="text-center animate-fade-in-up">
            <div className="inline-flex items-center gap-2 px-3 py-1 sm:px-4 sm:py-2 bg-primary/10 dark:bg-primary/20 rounded-full border border-primary/20 dark:border-slate-900/30 mb-3 sm:mb-4">
              <Sparkles className="w-3 h-3 sm:w-4 sm:h-4 text-primary dark:text-slate-900" />
              <span className="text-xs sm:text-sm font-medium text-primary dark:text-white">Actionable Feedback</span>
            </div>
            <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground dark:text-white mb-2 sm:mb-3">
              Feedback & Suggestions
            </h1>
            <p className="text-sm sm:text-base text-muted-foreground dark:text-muted-foreground max-w-2xl mx-auto px-2 sm:px-0 leading-relaxed">
              Personalized recommendations to enhance your resume and boost your job search success.
            </p>
          </div>

          {/* Stats and Controls */}
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-between items-stretch sm:items-center mb-4 sm:mb-6 animate-fade-in-up overflow-hidden">
            <div className="flex flex-col sm:flex-row gap-3 sm:gap-4">
              {/* Item Counter */}
              <div className="flex items-center gap-2 bg-muted dark:bg-muted rounded-lg px-3 py-2 border border-border dark:border-border w-full sm:w-auto justify-center sm:justify-start">
                <Filter className="w-3 h-3 sm:w-4 sm:h-4 text-muted-foreground dark:text-muted-foreground" />
                <span className="text-sm font-medium text-foreground dark:text-white">{filtered.length} items</span>
              </div>

              {/* Priority Legend - Hidden on mobile, shown on sm+ */}
              <div className="hidden sm:flex items-center gap-3">
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2 bg-error rounded-full"></div>
                  <span className="text-xs text-muted-foreground dark:text-muted-foreground">High</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2 bg-secondary rounded-full"></div>
                  <span className="text-xs text-muted-foreground dark:text-muted-foreground">Medium</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2 bg-primary rounded-full"></div>
                  <span className="text-xs text-muted-foreground dark:text-muted-foreground">Low</span>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-2 sm:gap-3 w-full sm:w-auto">
              <button
                onClick={() => setIsModalOpen(true)}
                className="btn-secondary flex items-center justify-center gap-2 hover:scale-105 transition-transform text-xs sm:text-sm py-2.5 flex-1 sm:flex-initial"
                disabled={feedbackItems.length === 0}
              >
                <Eye className="w-3 h-3 sm:w-4 sm:h-4" />
                <span>Popup View</span>
              </button>
              <button
                onClick={handleDownloadFeedback}
                disabled={feedbackItems.length === 0 || isLoading}
                className="btn-primary flex items-center justify-center gap-2 hover:scale-105 transition-transform disabled:opacity-60 disabled:cursor-not-allowed text-xs sm:text-sm py-2.5 flex-1 sm:flex-initial"
              >
                <Download className="w-3 h-3 sm:w-4 sm:h-4" />
                <span>Download PDF</span>
              </button>
            </div>
          </div>

          {/* Loading State */}
          {isLoading && (
            <div className="card-base animate-fade-in-up border border-dashed border-primary/40 dark:border-slate-900/40 bg-primary/5 dark:bg-primary/10 rounded-xl p-4 sm:p-6 flex items-center gap-3 sm:gap-4 overflow-hidden">
              <Loader2 className="w-6 h-6 sm:w-8 sm:h-8 animate-spin text-primary dark:text-slate-900 flex-shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="font-semibold text-foreground dark:text-white text-base sm:text-lg mb-1">
                  Generating Feedback...
                </p>
                <p className="text-xs sm:text-sm text-muted-foreground dark:text-muted-foreground">
                  We're analyzing your resume to provide actionable suggestions and improvements.
                </p>
              </div>
            </div>
          )}

          {/* Error State */}
          {!isLoading && error && (
            <div className="card-base animate-fade-in-up border-l-3 sm:border-l-4 border-l-error dark:border-l-error bg-error/5 dark:bg-error/10 rounded-xl p-4 sm:p-6 overflow-hidden">
              <div className="flex items-center gap-3 mb-3">
                <AlertTriangle className="w-5 h-5 sm:w-6 sm:h-6 text-error flex-shrink-0" />
                <h3 className="font-semibold text-foreground dark:text-white text-base sm:text-lg">
                  Feedback Generation Failed
                </h3>
              </div>
              <p className="text-error/80 dark:text-error/70 mb-4 text-sm sm:text-base">{error}</p>
              <button
                onClick={handleRetry}
                className="btn-secondary flex items-center justify-center gap-2 hover:scale-105 transition-transform text-sm w-full sm:w-auto"
              >
                <Zap className="w-3 h-3 sm:w-4 sm:h-4" />
                Try Again
              </button>
            </div>
          )}

          {/* Filter Tabs */}
          {!isLoading && !error && feedbackItems.length > 0 && (
            <div className="animate-fade-in-up overflow-hidden">
              <div className="flex gap-1 sm:gap-2 overflow-x-auto pb-3 sm:pb-4 scrollbar-hide">
                {categories.map((filter) => (
                  <button
                    key={filter}
                    onClick={() => setActiveFilter(filter)}
                    className={`px-3 sm:px-4 py-2 sm:py-3 rounded-lg sm:rounded-xl font-medium whitespace-nowrap transition-all duration-200 flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm ${
                      activeFilter === filter
                        ? "bg-primary dark:bg-primary text-white dark:text-white shadow-lg shadow-primary/30 dark:shadow-primary/20 scale-105"
                        : "bg-muted dark:bg-muted text-foreground dark:text-foreground hover:bg-border dark:hover:bg-border hover:shadow-md"
                    }`}
                  >
                    {filter === "all" ? (
                      <>
                        <Target className="w-3 h-3 sm:w-4 sm:h-4" />
                        <span className="hidden xs:inline">All</span>
                      </>
                    ) : (
                      filter.charAt(0).toUpperCase() + filter.slice(1)
                    )}
                  </button>
                ))}
              </div>

              {/* Feedback Items */}
              <div className="space-y-3 sm:space-y-4 mt-3 sm:mt-4 overflow-hidden">
                {filtered.map((item, i) => (
                  <div
                    key={item.id}
                    className={`card-base border-l-3 sm:border-l-4 rounded-xl p-4 sm:p-6 hover:shadow-md transition-all duration-300 animate-fade-in-up group overflow-hidden ${
                      item.priority === "high"
                        ? "border-l-error dark:border-l-error"
                        : item.priority === "medium"
                          ? "border-l-secondary dark:border-l-secondary"
                          : "border-l-primary dark:border-l-primary"
                    }`}
                    style={{ animationDelay: `${i * 50}ms` }}
                  >
                    <div className="flex flex-col sm:flex-row sm:items-start justify-between mb-3 gap-3 sm:gap-4">
                      <div className="flex-1 min-w-0">
                        <h3 className="font-bold text-foreground dark:text-white text-base sm:text-lg mb-2 leading-tight">
                          {item.title}
                        </h3>
                        <div className="flex flex-wrap gap-2">
                          <span className="text-xs font-medium text-primary dark:text-white bg-primary/10 dark:bg-primary/20 px-2 py-1 sm:px-3 sm:py-1 rounded-full border border-primary/20 dark:border-slate-900/30">
                            {item.category}
                          </span>
                          <span
                            className={`text-xs font-medium px-2 py-1 sm:px-3 sm:py-1.5 rounded-full border ${getPriorityColor(item.priority)}`}
                          >
                            {item.priority} priority
                          </span>
                        </div>
                      </div>
                      <button
                        onClick={() => handleCopy(item.id)}
                        className="flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm text-primary dark:text-white hover:text-primary/80 dark:hover:text-slate-100 transition-colors bg-background/80 dark:bg-background/80 backdrop-blur-sm rounded-lg px-2.5 py-1.5 sm:px-3 sm:py-2 border border-border dark:border-border hover:border-primary/30 dark:hover:border-slate-900/30 hover:scale-105 transition-transform w-full sm:w-auto"
                      >
                        {copiedId === item.id ? (
                          <>
                            <Check className="w-3 h-3 sm:w-4 sm:h-4" />
                            <span>Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3 sm:w-4 sm:h-4" />
                            <span>Copy</span>
                          </>
                        )}
                      </button>
                    </div>
                    <p className="text-foreground dark:text-white leading-relaxed text-sm sm:text-base">
                      {item.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Empty State */}
          {!isLoading && !error && feedbackItems.length === 0 && (
            <div className="card-base animate-fade-in-up border border-dashed border-muted-foreground/30 dark:border-muted-foreground/30 bg-muted/30 dark:bg-muted/20 text-muted-foreground dark:text-muted-foreground rounded-xl p-6 sm:p-8 text-center overflow-hidden">
              <Lightbulb className="w-8 h-8 sm:w-10 sm:h-10 mx-auto mb-2 sm:mb-3 opacity-50" />
              <p className="font-medium text-base sm:text-lg mb-1 sm:mb-2">No feedback available yet</p>
              <p className="text-xs sm:text-sm max-w-md mx-auto">
                We need more details in your resume to generate meaningful feedback. Try expanding your experience or
                skills sections.
              </p>
            </div>
          )}

          {/* Enhanced Navigation */}
          <div className="flex flex-col sm:flex-row gap-3 justify-between mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-border dark:border-border overflow-hidden">
            <button
              onClick={onPrevious}
              className="btn-secondary flex items-center justify-center gap-2 order-2 sm:order-1 hover:scale-105 transition-transform py-2.5 sm:py-3 text-sm w-full sm:w-auto"
            >
              <ArrowLeft className="w-3 h-3 sm:w-4 sm:h-4" />
              Back to Analysis
            </button>
            <button
              onClick={() => onNext()}
              className="btn-primary flex items-center justify-center gap-2 order-1 sm:order-2 hover:scale-105 transition-transform py-2.5 sm:py-3 text-sm w-full sm:w-auto"
            >
              Check Keywords
              <ArrowRight className="w-3 h-3 sm:w-4 sm:h-4" />
            </button>
          </div>

          <FeedbackModal
            isOpen={isModalOpen}
            onClose={() => setIsModalOpen(false)}
            feedbackItems={feedbackItems}
            onDownload={handleDownloadFeedback}
          />
        </div>
      </div>
    </div>
  )
}
